name: CI Security

on:
  push:
  workflow_dispatch:
  pull_request:
  
permissions:
  security-events: write
  packages: read
  actions: read
  contents: read
jobs:
  
  SAST:
    runs-on: ubuntu-latest
    name: Static Application Security Testing
    steps:   
    
      - name: Git Clone
        uses: actions/checkout@v4
      
      - name: Mvn dependency tree
        run: mvn dependency:tree
  
