name: CI Security

on:
  push:
  workflow_dispatch:
permissions:
  security-events: write
  packages: read
  actions: read
  contents: read
jobs:
  
  SAST:
    runs-on: ubuntu-latest
    steps:   
    
      - name: Git Clone
        uses: actions/checkout@v4
      
      - name: Set Up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: none
    
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java-kotlin"
 
  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:
  
      - name: SCA Analysis
        run: |
          echo "SCA"
          
  Docker-build:
    needs: 
    - SAST
    - SCA
    runs-on: ubuntu-latest
    steps:
    
      - name: Docker Auth
        run: |
          echo "Docker login"

      - name: Docker Config
        uses: docker/setup-buildx-action@v3
      
      - name: Construccion Imagen
        run: | 
          #docker build -t clagosu/ms-aumento-voto:latest .
          echo "Docker build"

  Container-Analysis:
    needs: Docker-build
    runs-on: ubuntu-latest
    steps:
    
      - name: Image Analysis
        run: |
          docker pull clagosu/ms-aumento-voto:latest
                  - name: Aqua Security Trivy
      - name: Vulnerability Analysis
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'clagosu/ms-aumento-voto:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
  Docker-push:
    needs: 
      - Container-Analysis
    runs-on: ubuntu-latest
    steps:
    
      - name: Docker push
        run: |
          echo "Docker push"
  
